// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uHQW2pvgnMYkU9Giixod5o
// Component: ZmBvv8sxrP0d

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantsgt9QMo0RuEb7 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: GT9qMO0RUEb7/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: uHQW2pvgnMYkU9Giixod5o/projectcss
import sty from "./PlasmicInstagram.module.css"; // plasmic-import: ZmBvv8sxrP0d/css

import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: XXG-MBaBsioY/icon

createPlasmicElementProxy;

export type PlasmicInstagram__VariantMembers = {};
export type PlasmicInstagram__VariantsArgs = {};
type VariantPropType = keyof PlasmicInstagram__VariantsArgs;
export const PlasmicInstagram__VariantProps = new Array<VariantPropType>();

export type PlasmicInstagram__ArgsType = {};
type ArgPropType = keyof PlasmicInstagram__ArgsType;
export const PlasmicInstagram__ArgProps = new Array<ArgPropType>();

export type PlasmicInstagram__OverridesType = {
  root?: Flex__<"section">;
  h3?: Flex__<"h3">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  text?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultInstagramProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInstagram__RenderFunc(props: {
  variants: PlasmicInstagram__VariantsArgs;
  args: PlasmicInstagram__ArgsType;
  overrides: PlasmicInstagram__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgt9QMo0RuEb7()
  });

  return (
    <Stack__
      as={"section"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__lv2RW)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__xuATr)}
        >
          <h3
            data-plasmic-name={"h3"}
            data-plasmic-override={overrides.h3}
            className={classNames(
              projectcss.all,
              projectcss.h3,
              projectcss.__wab_text,
              sty.h3
            )}
          >
            {"Follow us on Instagram for \nmore updates"}
          </h3>
          <Stack__
            as={PlasmicLink__}
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            hasGap={true}
            className={classNames(projectcss.all, projectcss.a, sty.link)}
            component={Link}
            href={`/item`}
            platform={"nextjs"}
          >
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {"See more product"}
            </div>
            <RightArrowIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />
          </Stack__>
        </Stack__>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__lllvb)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__jtEx3)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__qfnWy)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "250px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: "/plasmic/commerce_storefront/images/_11Png.png",
              fullWidth: 544,
              fullHeight: 544,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__b1R3Y)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__xfSvB)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "250px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: "/plasmic/commerce_storefront/images/_2Jpg.jpg",
              fullWidth: 640,
              fullHeight: 640,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__rgJF)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__spW26)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "250px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: "/plasmic/commerce_storefront/images/_3Jpg.jpg",
              fullWidth: 430,
              fullHeight: 426,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__sQqNn)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__h31LM)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "250px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: "/plasmic/commerce_storefront/images/_4Jpg.jpg",
              fullWidth: 406,
              fullHeight: 400,
              aspectRatio: undefined
            }}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__ieplg)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__np3Ra)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "250px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "auto"
                : "100%"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/commerce_storefront/images/_5Jpg.jpg",
              fullWidth: 640,
              fullHeight: 639,
              aspectRatio: undefined
            }}
          />
        </div>
      </Stack__>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h3", "link", "text", "svg"],
  h3: ["h3"],
  link: ["link", "text", "svg"],
  text: ["text"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "section";
  h3: "h3";
  link: "a";
  text: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInstagram__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInstagram__VariantsArgs;
    args?: PlasmicInstagram__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicInstagram__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicInstagram__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicInstagram__ArgProps,
          internalVariantPropNames: PlasmicInstagram__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicInstagram__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInstagram";
  } else {
    func.displayName = `PlasmicInstagram.${nodeName}`;
  }
  return func;
}

export const PlasmicInstagram = Object.assign(
  // Top-level PlasmicInstagram renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),
    link: makeNodeComponent("link"),
    text: makeNodeComponent("text"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicInstagram
    internalVariantProps: PlasmicInstagram__VariantProps,
    internalArgProps: PlasmicInstagram__ArgProps
  }
);

export default PlasmicInstagram;
/* prettier-ignore-end */
