// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uHQW2pvgnMYkU9Giixod5o
// Component: ayrlMeEPbN2C

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ProductMedia } from "@plasmicpkgs/commerce";
import { ProductTextField } from "@plasmicpkgs/commerce";
import { ProductPriceComponent } from "@plasmicpkgs/commerce";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: uHQW2pvgnMYkU9Giixod5o/projectcss
import sty from "./PlasmicProductMain.module.css"; // plasmic-import: ayrlMeEPbN2C/css

createPlasmicElementProxy;

export type PlasmicProductMain__VariantMembers = {};
export type PlasmicProductMain__VariantsArgs = {};
type VariantPropType = keyof PlasmicProductMain__VariantsArgs;
export const PlasmicProductMain__VariantProps = new Array<VariantPropType>();

export type PlasmicProductMain__ArgsType = {};
type ArgPropType = keyof PlasmicProductMain__ArgsType;
export const PlasmicProductMain__ArgProps = new Array<ArgPropType>();

export type PlasmicProductMain__OverridesType = {
  root?: Flex__<"a"> & Partial<LinkProps>;
  productMedia?: Flex__<typeof ProductMedia>;
  h3?: Flex__<"h3">;
  h5?: Flex__<"h5">;
  productPrice?: Flex__<typeof ProductPriceComponent>;
};

export interface DefaultProductMainProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProductMain__RenderFunc(props: {
  variants: PlasmicProductMain__VariantsArgs;
  args: PlasmicProductMain__ArgsType;
  overrides: PlasmicProductMain__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        "cover-container"
      )}
      component={Link}
      href={`/item`}
      platform={"nextjs"}
    >
      <ProductMedia
        data-plasmic-name={"productMedia"}
        data-plasmic-override={overrides.productMedia}
        className={classNames("__wab_instance", sty.productMedia)}
      />

      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__al8Jd)}
      >
        <h3
          data-plasmic-name={"h3"}
          data-plasmic-override={overrides.h3}
          className={classNames(projectcss.all, projectcss.h3, sty.h3)}
        >
          <ProductTextField
            className={classNames(
              "__wab_instance",
              sty.productTextField___5KMb
            )}
            field={"name"}
          />
        </h3>
        <div className={classNames(projectcss.all, sty.freeBox__zhTJo)}>
          <ProductTextField
            className={classNames("__wab_instance", sty.productTextField__oy9G)}
            field={"description"}
          />
        </div>
        <h5
          data-plasmic-name={"h5"}
          data-plasmic-override={overrides.h5}
          className={classNames(projectcss.all, projectcss.h5, sty.h5)}
        >
          <ProductPriceComponent
            data-plasmic-name={"productPrice"}
            data-plasmic-override={overrides.productPrice}
            className={classNames("__wab_instance", sty.productPrice)}
          />
        </h5>
      </Stack__>
    </PlasmicLink__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "productMedia", "h3", "h5", "productPrice"],
  productMedia: ["productMedia"],
  h3: ["h3"],
  h5: ["h5", "productPrice"],
  productPrice: ["productPrice"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "a";
  productMedia: typeof ProductMedia;
  h3: "h3";
  h5: "h5";
  productPrice: typeof ProductPriceComponent;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProductMain__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProductMain__VariantsArgs;
    args?: PlasmicProductMain__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProductMain__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProductMain__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProductMain__ArgProps,
          internalVariantPropNames: PlasmicProductMain__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProductMain__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductMain";
  } else {
    func.displayName = `PlasmicProductMain.${nodeName}`;
  }
  return func;
}

export const PlasmicProductMain = Object.assign(
  // Top-level PlasmicProductMain renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    productMedia: makeNodeComponent("productMedia"),
    h3: makeNodeComponent("h3"),
    h5: makeNodeComponent("h5"),
    productPrice: makeNodeComponent("productPrice"),

    // Metadata about props expected for PlasmicProductMain
    internalVariantProps: PlasmicProductMain__VariantProps,
    internalArgProps: PlasmicProductMain__ArgProps
  }
);

export default PlasmicProductMain;
/* prettier-ignore-end */
